/**
 * Review Formatter — Converts structured LLM output into markdown for PR comments.
 */
const SEVERITY_EMOJI = { high: "🔴", medium: "🟡", low: "🔵" };
const TYPE_LABEL = {
  performance: "⚡ Performance",
  bug: "🐛 Bug",
  readability: "📖 Readability",
  security: "🔒 Security",
  accessibility: "♿ Accessibility",
  "anti-pattern": "🚫 Anti-pattern",
};

function formatReview(issues) {
  if (!issues.length) return "✅ **AI Code Review**: No issues found.";

  const sorted = [...issues].sort((a, b) => severityRank(b) - severityRank(a));

  const highCount = sorted.filter((i) => i.severity === "high").length;
  const medCount = sorted.filter((i) => i.severity === "medium").length;

  let output = `## 🤖 AI Code Review\n\n`;
  output += `**${issues.length} issue(s) found** — ${highCount} high, ${medCount} medium, ${issues.length - highCount - medCount} low\n\n`;
  output += `---\n\n`;

  for (const issue of sorted) {
    const emoji = SEVERITY_EMOJI[issue.severity] || "⚪";
    const type = TYPE_LABEL[issue.type] || issue.type;
    const location = issue.line
      ? `\`${issue.file}:${issue.line}\``
      : `\`${issue.file}\``;

    output += `${emoji} **[${issue.severity.toUpperCase()}]** ${type} — ${location}\n`;
    output += `> ${issue.suggestion}\n\n`;
  }

  output += `---\n*Generated by Code Review Agent*`;
  return output;
}

function severityRank(issue) {
  return { high: 3, medium: 2, low: 1 }[issue.severity] || 0;
}

module.exports = { formatReview };
